dist: trusty

language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
  - composer install --no-interaction

script:
  - find src/ tests/ -type f -name '*.php' -print0|xargs -0 -L1 -P4 -- php -l
  - if [[ $(phpenv version-name) == 7.3 ]]; then phpcs; fi
  - vendor/bin/phpunit
