dist: trusty

language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - composer self-update

install:
  - composer install --no-interaction

script:
  - find src tests \( -name '*.php' \) -exec php -l {} \;
  - if [[ $TRAVIS_PHP_VERSION == "7.3" ]]; then phpcs; fi
  - vendor/bin/phpunit
